repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
        stages: ["commit"]
      - id: check-ast
        stages: ["commit"]
      - id: check-toml
        stages: ["commit"]
      - id: check-xml
        stages: ["commit"]
      - id: check-yaml
        stages: ["commit"]
      - id: debug-statements
        stages: ["commit"]
      - id: requirements-txt-fixer
        stages: ["commit"]
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        stages: ["commit"]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        stages: ["commit"]
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--expand-star-imports",
            "--ignore-init-module-imports",
          ]
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.10.1
  #   hooks:
  #     - id: isort
  #       stages: ["commit"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language: python
        stages: ["commit"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1"
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|less|html|json|markdown|md|yaml|yml)$
        stages: ["commit"]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow
  - repo: https://github.com/PyCQA/prospector
    rev: 1.10.2
    hooks:
      - id: prospector
        stages: [push]
