version: "3.8"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery-worker:
    build:
      context: celery
      dockerfile: Dockerfile
    volumes:
      - ./celery:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    command: celery -A src.worker worker --loglevel=info
    restart: on-failure

  taskiq-worker:
    build:
      context: taskiq
      dockerfile: Dockerfile
    volumes:
      - ./taskiq:/app
    depends_on:
      - redis
    command: taskiq worker src.worker:broker
    restart: on-failure

  flower:
    build:
      context: celery
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - ./celery:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - celery-worker
    command: celery -A src.worker flower --loglevel=info
    restart: on-failure

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 3
    restart: always

volumes:
  redis_data:
